import Cabecalho from "@/components/Cabecalho/Cabecalho";
import Menu from "@/components/Menu/Menu";
import Rodape from "@/components/Rodape/Rodape";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "CP6",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        {children}

      </body>
    </html>
  );
}
